# Generated by Django 2.2 on 2022-06-07 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
